### PR TITLE
Fix table name while query list

### PR DESCRIPTION
**Pull request by dawndiy**
Fix custom tableName while query list

### CODE REVIEW

**Comment by hsluoyz** [comment]
@dawndiy please fix "Merge branch xxx", DCO and CI:

image

**Comment by dawndiy** [comment]
@hsluoyz The DOC is passed, but the Travis CI is always failed. Please look at it.

**Comment by hsluoyz** [comment]
@dawndiy it seems that your PR failed the CI, please fix it.

**Comment by dawndiy** [comment]
@hsluoyz I'm very sure that was not this PR make the CI failed.  #34 this PR removes lots of dependent modules, that make the CI failed, but I'm fixed now. Please look at it.

**Comment by hsluoyz** [comment]
@dawndiy got it. Thanks for the fix!

**Pull request merged**
