### PR TITLE
Updated to casbin v2 and use strings.Builder

### PR DESCRIPTION
**Pull request by ctxnop**
Updated imports to be used with casbin v2.
Also, use a strings.Builder when building some string to reduce garbage
collection workload.

Change-Id: I96a75f06fb1985b1ab2d2808ee3928aa7be48df3
Signed-off-by: Loïc Collignon <loic.collignon@iot.bzh>

### CODE REVIEW

**Comment by ctxnop** [comment]
It compiles and works on my side. The only diff is that I have a go.mod file, should I add it to the commit?

**Comment by hsluoyz** [comment]
Hi @ctxnop , please commit the ``go.mod`` file. Also please fix the CI error.

**Comment by ctxnop** [comment]
That's the point: I don't get what is the reason of the CI error.
I'll add the go.mod tomorrow to check if it's enough to fix the CI error.

**Comment by hsluoyz** [comment]
You need to commit both go.mod and go.sum to fix the CI error.

**Comment by hsluoyz** [comment]
@ctxnop , ``adapter_test.go`` should also import Casbin v2.x path.

**Comment by ctxnop** [comment]
Off course... silly me... sorry for the miss,
I'll fix the adapter_test

**Comment by ctxnop** [comment]
Humm... When I do a ```go test``` everything is passing...
It seems that it's a postgresql issue here, either it's not started or not acccepting connection. No?

**Comment by hsluoyz** [comment]
@ctxnop , that's the problem. I have fixed it in: https://github.com/casbin/xorm-adapter/commit/af09ce67e18640937cd62cbf0960daa71795d1a9

**Pull request merged**
